/* eslint-disable import/extensions */
import * as chai from 'chai';
import corpus from './data/iana-corpus.json';
import { Address4 } from '../src/ipv4';
import { Address6 } from '../src/ipv6';

const should = chai.should();

// test/data/iana-corpus.json is generated by scripts/gen-iana-corpus.py from
// the IANA special-purpose address registries checked in beside it. Every
// probe is a boundary of a registry block (or an IPv4-mapped / NAT64 form of
// one) with the registry's own answer attached, so this suite fails when the
// classifiers disagree with the registry rather than when a reporter notices.
//
// Python's ipaddress classification rides along for cross-checking; it
// disagrees with the registry on a few rows (see PYTHON_DISAGREES).

interface Probe {
  address: string;
  family: 4 | 6;
  block: string | null;
  embedded?: string;
  global: boolean;
  python: {
    loopback: boolean;
    linkLocal: boolean;
    multicast: boolean;
    unspecified: boolean;
    global: boolean;
  };
}

const probes = corpus as Probe[];

// Blocks where Python 3.14's ipaddress and the registry disagree on global
// reachability. The registry is the authority here.
const PYTHON_DISAGREES: Array<Address4 | Address6> = [
  new Address4('192.88.99.2/32'), // 6a44-relay anycast: registry false, Python true
  new Address6('100:0:0:1::/64'), // Dummy IPv6 Prefix: registry false, Python true
  new Address6('2001:1::3/128'), // DNS-SD SRP anycast: registry true, Python false
  new Address6('5f00::/16'), // SRv6 SIDs: registry false, Python true
];

function parse(probe: Probe): Address4 | Address6 {
  return probe.family === 4 ? new Address4(probe.address) : new Address6(probe.address);
}

// Python classifies the NAT64 well-known prefix by its IPv6 block; the
// library, like the mapped form, answers for the embedded IPv4 address, so
// Python's view of those probes is not comparable.
function pythonComparable(address: Address4 | Address6): boolean {
  return !(address instanceof Address6 && address.embeddedIPv4() && !address.isMapped4());
}

function inException(address: Address4 | Address6): boolean {
  const embedded = address instanceof Address6 ? address.embeddedIPv4() : null;
  const subject = embedded ?? address;
  return PYTHON_DISAGREES.some(
    (subnet) =>
      subnet.constructor === subject.constructor && subject.isHostInSubnet(subnet as never),
  );
}

describe('IANA special-purpose registry corpus', () => {
  it('has probes from both registries', () => {
    probes.filter((p) => p.family === 4).length.should.be.greaterThan(100);
    probes.filter((p) => p.family === 6).length.should.be.greaterThan(100);
  });

  it('isGlobal() agrees with the registry on every probe', () => {
    probes.forEach((probe) => {
      should.equal(parse(probe).isGlobal(), probe.global, `${probe.address} (${probe.block})`);
    });
  });

  it('isLoopback, isLinkLocal, isMulticast, and isUnspecified agree with Python', () => {
    probes.forEach((probe) => {
      const address = parse(probe);
      if (!pythonComparable(address)) {
        return;
      }

      const context = `${probe.address} (${probe.block})`;
      should.equal(address.isLoopback(), probe.python.loopback, context);
      should.equal(address.isLinkLocal(), probe.python.linkLocal, context);
      should.equal(address.isMulticast(), probe.python.multicast, context);
      should.equal(address.isUnspecified(), probe.python.unspecified, context);
    });
  });

  it('isGlobal() agrees with Python outside the documented exceptions', () => {
    probes.forEach((probe) => {
      const address = parse(probe);
      if (!pythonComparable(address) || inException(address)) {
        return;
      }

      // Python calls multicast global; the library does not.
      should.equal(
        address.isGlobal(),
        probe.python.global && !probe.python.multicast,
        `${probe.address} (${probe.block})`,
      );
    });
  });

  it('every documented exception still disagrees', () => {
    // Delete the entry from PYTHON_DISAGREES once Python and the registry agree.
    PYTHON_DISAGREES.forEach((subnet) => {
      const inside = probes.filter((probe) => {
        const address = parse(probe);
        return (
          !probe.embedded &&
          subnet.constructor === address.constructor &&
          address.isHostInSubnet(subnet as never)
        );
      });
      inside.length.should.be.greaterThan(0, subnet.address);
      inside
        .some((probe) => probe.python.global !== probe.global)
        .should.equal(true, `${subnet.address}: Python now agrees with the registry`);
    });
  });
});
