recursive: true
reporter: spec
require:
- ts-node/register
- source-map-support/register
inline-diffs: false
spec: test/**/*.ts
extension: 'ts,json'
node-option:
- es-module-specifier-resolution=node
- loader=ts-node/esm
- no-warnings
